// NOTE : CE FICHIER NE DEVRAIT PAS SE RETROUVER SUR GITLAB PUISQU'IL CONTIENT DES DONNÉES SENSIBLES POUR LA CONNEXION À LA BASE DE DONNÉES
// TOUTEFOIS, POUR FACILITER LA CORRECTION, NOUS L'AVONS TOUT DE MÊME INCLUS

export const DATABASE_URL = 'mongodb+srv://databaseAdmin:SlIquPzL5ZQnC7UT@projet3.lngt7ve.mongodb.net/?retryWrites=true&w=majority';
export const DATABASE_NAME = 'ScrabbleLOG3900';
